category:
  per_page: 10
  per_word: 10
word:
  per_page: 20
word_filter: {learned: "learned", not_learned: "not_learned", all: "show_all"}
all: "All"
admin:
  category:
    per_page: 9
  words:
    default_size_word_answers: 4
    max_size_word_answers: 7
  users:
    per_page: 10
lesson:
  number_words: 10
  per_page: 10
size_icon_true_false: 30
relationships:
  per_page: 5
activities:
  per_page: 20
